In [ ]:
#import the numpy library
import numpy as np

In [9]:
#creating a 1D array
arry =np.array([1,2,3,4,5])
print(arry)
print(arry.dtype)

[1 2 3 4 5]
int64


In [12]:
#creating a 2D array
arry2=np.array([[1.5,2,3],[4,5.2,6],[7,8,9.1]])
print(arry2)
print(arry2.dtype)

[[1.5 2.  3. ]
 [4.  5.2 6. ]
 [7.  8.  9.1]]
float64


In [23]:
#creates an array of zeros
print(np.zeros((2,3)))
print("\n")

#creates an array of ones
print(np.ones((3,4)))
print("\n")

#creates an array with a range of values(start,stop,gap)
print(np.arange(0,10,2))

[[0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[0 2 4 6 8]


In [27]:
#array properties
arry=np.array([[1,2,3],[10,12,14],[100,200,300]])
print(arry.shape)
print(arry.size)
print(arry.ndim)
print(arry.dtype)

(3, 3)
9
2
int64


In [39]:
#array slicing and indexing
arry=np.array([[1,2,3],[10,12,14],[100,200,300]])
print(arry[0]) #first row
print(arry[1,2]) #element in second row and third column
print(arry[0:2]) #first two rows
print(arry[:,1]) #second column
print(arry[1:3,0:2]) #subarray of last two rows and first two columns

[1 2 3]
14
[[ 1  2  3]
 [10 12 14]]
[  2  12 200]
[[ 10  12]
 [100 200]]
